% https://www.swi-prolog.org/FAQ/Multifile.html
:- multifile prop/3.

prop(earthshaker, type, hero).
prop(sven, type, hero).
prop(tiny, type, hero).
prop(kunkka, type, hero).
prop(anti-mage, type, hero).
prop(drow_ranger, type, hero).
prop(juggernaut, type, hero).
prop(mirana, type, hero).
prop(crystal_maiden, type, hero).
prop(puck, type, hero).
prop(storm_spirit, type, hero).
prop(windranger, type, hero).
prop(beastmaster, type, hero).
prop(dragon_knight, type, hero).
prop(clockwerk, type, hero).
prop(omniknight, type, hero).
prop(morphling, type, hero).
prop(phantom_lancer, type, hero).
prop(vengeful_spirit, type, hero).
prop(riki, type, hero).
prop(zeus, type, hero).
prop(lina, type, hero).
prop(shadow_shaman, type, hero).
prop(tinker, type, hero).
prop(huskar, type, hero).
prop(alchemist, type, hero).
prop(brewmaster, type, hero).
prop(treant_protector, type, hero).
prop(sniper, type, hero).
prop(templar_assassin, type, hero).
prop(luna, type, hero).
prop(bounty_hunter, type, hero).
prop(natures_prophet, type, hero).
prop(enchantress, type, hero).
prop(jakiro, type, hero).
prop(chen, type, hero).
prop(io, type, hero).
prop(centaur_warrunner, type, hero).
prop(timbersaw, type, hero).
prop(bristleback, type, hero).
prop(ursa, type, hero).
prop(gyrocopter, type, hero).
prop(hoodwink, type, hero).
prop(lone_druid, type, hero).
prop(silencer, type, hero).
prop(ogre_magi, type, hero).
prop(rubick, type, hero).
prop(disruptor, type, hero).
prop(tusk, type, hero).
prop(elder_titan, type, hero).
prop(legion_commander, type, hero).
prop(earth_spirit, type, hero).
prop(naga_siren, type, hero).
prop(troll_warlord, type, hero).
prop(ember_spirit, type, hero).
prop(monkey_king, type, hero).
prop(keeper_of_the_light, type, hero).
prop(skywrath_mage, type, hero).
prop(oracle, type, hero).
prop(techies, type, hero).
prop(phoenix, type, hero).
prop(mars, type, hero).
prop(snapfire, type, hero).
prop(pangolier, type, hero).
prop(dark_willow, type, hero).
prop(void_spirit, type, hero).
prop(axe, type, hero).
prop(pudge, type, hero).
prop(sand_king, type, hero).
prop(slardar, type, hero).
prop(bloodseeker, type, hero).
prop(shadow_fiend, type, hero).
prop(razor, type, hero).
prop(venomancer, type, hero).
prop(bane, type, hero).
prop(lich, type, hero).
prop(lion, type, hero).
prop(witch_doctor, type, hero).
prop(tidehunter, type, hero).
prop(wraith_king, type, hero).
prop(lifestealer, type, hero).
prop(night_stalker, type, hero).
prop(faceless_void, type, hero).
prop(phantom_assassin, type, hero).
prop(viper, type, hero).
prop(clinkz, type, hero).
prop(enigma, type, hero).
prop(necrophos, type, hero).
prop(warlock, type, hero).
prop(queen_of_pain, type, hero).
prop(doom, type, hero).
prop(spirit_breaker, type, hero).
prop(lycan, type, hero).
prop(chaos_knight, type, hero).
prop(broodmother, type, hero).
prop(weaver, type, hero).
prop(spectre, type, hero).
prop(meepo, type, hero).
prop(death_prophet, type, hero).
prop(pugna, type, hero).
prop(dazzle, type, hero).
prop(leshrac, type, hero).
prop(undying, type, hero).
prop(magnus, type, hero).
prop(abaddon, type, hero).
prop(underlord, type, hero).
prop(nyx_assassin, type, hero).
prop(slark, type, hero).
prop(medusa, type, hero).
prop(terrorblade, type, hero).
prop(dark_seer, type, hero).
prop(batrider, type, hero).
prop(ancient_apparition, type, hero).
prop(invoker, type, hero).
prop(arc_warden, type, hero).
prop(outworld_destroyer, type, hero).
prop(shadow_demon, type, hero).
prop(visage, type, hero).
prop(winter_wyvern, type, hero).
prop(grimstroke, type, hero).
