% https://www.swi-prolog.org/FAQ/Multifile.html
:- multifile prop/3.

% Carry
prop(abaddon , role, carry).
prop(alchemist , role, carry).
prop(axe , role, carry).
prop(brewmaster , role, carry).
prop(bristleback , role, carry).
prop(chaos_knight , role, carry).
prop(doom , role, carry).
prop(dragon_knight , role, carry).
prop(huskar , role, carry).
prop(kunkka , role, carry).
prop(legion_commander , role, carry).
prop(lifestealer , role, carry).
prop(lycan , role, carry).
prop(mars , role, carry).
prop(night_stalker , role, carry).
prop(stardar , role, carry).
prop(spirit_breaker , role, carry).
prop(sven , role, carry).
prop(tidehunter , role, carry).
prop(tiny , role, carry).
prop(wraith_king , role, carry).
prop('anti-mage', role, carry).
prop(arc_warden, role, carry).
prop(bloodseeker, role, carry).
prop(broodmother, role, carry).
prop(clinkz, role, carry).
prop(drow_ranger, role, carry).
prop(ember_spirit, role, carry).
prop(faceless_void, role, carry).
prop(gyrocopter, role, carry).
prop(juggernaut, role, carry).
prop(lone_druid, role, carry).
prop(luna, role, carry).
prop(medusa, role, carry).
prop(meepo, role, carry).
prop(mirana, role, carry).
prop(monkey_king, role, carry).
prop(morphing, role, carry).
prop(naga_siren, role, carry).
prop(pangolier, role, carry).
prop(phantom_assassin, role, carry).
prop(phantom_lancer, role, carry).
prop(razor, role, carry).
prop(riki, role, carry).
prop(shadow_fiend, role, carry).
prop(stark, role, carry).
prop(sniper, role, carry).
prop(spectre, role, carry).
prop(templar_assassin, role, carry).
prop(terrorblade, role, carry).
prop(troll_warlord, role, carry).
prop(ursa, role, carry).
prop(viper, role, carry).
prop(weaver, role, carry).
prop(death_prophet, role, carry).
prop(invoker, role, carry).
prop(leshrac, role, carry).
prop(lina, role, carry).
prop(natures_prophet, role, carry).
prop(necrophos, role, carry).
prop(outworld_destroyer, role, carry).
prop(queen_of_pain, role, carry).
prop(silencer, role, carry).
prop(storm_spirit, role, carry).
prop(tinker, role, carry).
prop(void_spirit, role, carry).
prop(windranger, role, carry).
prop(zeus, role, carry).

% Support
prop(abaddon, role, support).
prop(alchemist, role, support).
prop(earthshaker, role, support).
prop(io, role, support).
prop(kunkka, role, support).
prop(omniknight, role, support).
prop(phoenix, role, support).
prop(sand_king, role, support).
prop(snapfire, role, support).
prop(treant_protector, role, support).
prop(underlord, role, support).
prop(undying, role, support).
prop(wraith_king, role, support).
prop(mirana, role, support).
prop(naga_siren, role, support).
prop(vengeful_spirit, role, support).
prop(venomancer, role, support).
prop(ancient_apparition, role, support).
prop(bane, role, support).
prop(chen, role, support).
prop(crystal_maiden, role, support).
prop(dark_willow, role, support).
prop(dazzle, role, support).
prop(disruptor, role, support).
prop(enchantress, role, support).
prop(grimstroke, role, support).
prop(jakiro, role, support).
prop(keeper_of_the_light, role, support).
prop(leshrac, role, support).
prop(lich, role, support).
prop(lina, role, support).
prop(lion, role, support).
prop(ogre_magi, role, support).
prop(oracle, role, support).
prop(rubick, role, support).
prop(shadow_demon, role, support).
prop(shadow_shaman, role, support).
prop(silencer, role, support).
prop(skywrath_mage, role, support).
prop(visage, role, support).
prop(warlock, role, support).
prop(windranger, role, support).
prop(winter_wyvern, role, support).
prop(witch_doctor, role, support).

% Nuker
prop(alchemist, role, nuker).
prop(beastmaster, role, nuker).
prop(brewmaster, role, nuker).
prop(bristleback, role, nuker).
prop(centaur_warrunner, role, nuker).
prop(clockwerk, role, nuker).
prop(doom, role, nuker).
prop(dragon_knight, role, nuker).
prop(earth_spirit, role, nuker).
prop(earthshaker, role, nuker).
prop(elder_titan, role, nuker).
prop(io, role, nuker).
prop(kunkka, role, nuker).
prop(legion_commander, role, nuker).
prop(magnus, role, nuker).
prop(night_stalker, role, nuker).
prop(omniknight, role, nuker).
prop(phoenix, role, nuker).
prop(pudge, role, nuker).
prop(sand_king, role, nuker).
prop(snapfire, role, nuker).
prop(sven, role, nuker).
prop(tidehunter, role, nuker).
prop(timbersaw, role, nuker).
prop(tiny, role, nuker).
prop(tusk, role, nuker).
prop(underlord, role, nuker).
prop(undying, role, nuker).
prop('anti-mage', role, nuker).
prop(arc-warden, role, nuker).
prop(bloodseeker, role, nuker).
prop(bounty_hunter, role, nuker).
prop(broodmother, role, nuker).
prop(ember_spirit, role, nuker).
prop(gyrocopter, role, nuker).
prop(hoodwink, role, nuker).
prop(luna, role, nuker).
prop(meepo, role, nuker).
prop(mirana, role, nuker).
prop(morphling, role, nuker).
prop(nyx_assassin, role, nuker).
prop(pangolier, role, nuker).
prop(phantom_lancer, role, nuker).
prop(razor, role, nuker).
prop(shadow_fiend, role, nuker).
prop(slark, role, nuker).
prop(sniper, role, nuker).
prop(terrorblade, role, nuker).
prop(vengeful_spirit, role, nuker).
prop(venomancer, role, nuker).
prop(ancient_apparition, role, nuker).
prop(bane, role, nuker).
prop(crystal_maiden, role, nuker).
prop(dark_willow, role, nuker).
prop(dazzle, role, nuker).
prop(death_prophet, role, nuker).
prop(disruptor, role, nuker).
prop(grimstroke, role, nuker).
prop(invoker, role, nuker).
prop(jakiro, role, nuker).
prop(keeper_of_the_light, role, nuker).
prop(leshrac, role, nuker).
prop(lich, role, nuker).
prop(lina, role, nuker).
prop(lion, role, nuker).
prop(natures_prophet, role, nuker).
prop(necrophos, role, nuker).
prop(ogre_magi, role, nuker).
prop(oracle, role, nuker).
prop(outworld_destroyer, role, nuker).
prop(puck, role, nuker).
prop(pugna, role, nuker).
prop(queen_of_pain, role, nuker).
prop(rubick, role, nuker).
prop(shadow_demon, role, nuker).
prop(shadow_shaman, role, nuker).
prop(silencer, role, nuker).
prop(skywrath_mage, role, nuker).
prop(storm_spirit, role, nuker).
prop(techies, role, nuker).
prop(tinker, role, nuker).
prop(visage, role, nuker).
prop(void_spirit, role, nuker).
prop(windranger, role, nuker).
prop(winter_wyvern, role, nuker).
prop(witch_doctor, role, nuker).
prop(zeus, role, nuker).

% Disabler
prop(alchemist, role, disabler).
prop(axe, role, disabler).
prop(beastmaster, role, disabler).
prop(brewmaster, role, disabler).
prop(centaur_warrunner, role, disabler).
prop(chaos_knight, role, disabler).
prop(clockwerk, role, disabler).
prop(doom, role, disabler).
prop(dragon_knight, role, disabler).
prop(earth_spirit, role, disabler).
prop(earthshaker, role, disabler).
prop(elder_titan, role, disabler).
prop(kunkka, role, disabler).
prop(legion_commander, role, disabler).
prop(lifestealer, role, disabler).
prop(magnus, role, disabler).
prop(mars, role, disabler).
prop(night_stalker, role, disabler).
prop(phoenix, role, disabler).
prop(pudge, role, disabler).
prop(sand_king, role, disabler).
prop(stardar, role, disabler).
prop(snapfire, role, disabler).
prop(spirit_breaker, role, disabler).
prop(sven, role, disabler).
prop(tidehunter, role, disabler).
prop(tiny, role, disabler).
prop(treant_protector, role, disabler).
prop(tusk, role, disabler).
prop(underlord, role, disabler).
prop(undying, role, disabler).
prop(wraith_king, role, disabler).
prop(bloodseeker, role, disabler).
prop(drow_ranger, role, disabler).
prop(ember_spirit, role, disabler).
prop(faceless_void, role, disabler).
prop(gyrocopter, role, disabler).
prop(hoodwink, role, disabler).
prop(medusa, role, disabler).
prop(meepo, role, disabler).
prop(mirana, role, disabler).
prop(monkey_king, role, disabler).
prop(morphling, role, disabler).
prop(naga_siren, role, disabler).
prop(nyx_assassin, role, disabler).
prop(pangolier, role, disabler).
prop(riki, role, disabler).
prop(slark, role, disabler).
prop(troll_warlord, role, disabler).
prop(ursa, role, disabler).
prop(vengeful_spirit, role, disabler).
prop(venomancer, role, disabler).
prop(viper, role, disabler).
prop(ancient_apparition, role, disabler).
prop(bane, role, disabler).
prop(batrider, role, disabler).
prop(crystal_maiden, role, disabler).
prop(dark_seer, role, disabler).
prop(dark_willow, role, disabler).
prop(dazzle, role, disabler).
prop(death_prophet, role, disabler).
prop(disruptor, role, disabler).
prop(enchantress, role, disabler).
prop(enigma, role, disabler).
prop(grimstroke, role, disabler).
prop(invoker, role, disabler).
prop(jakiro, role, disabler).
prop(keeper_of_the_light, role, disabler).
prop(leshrac, role, disabler).
prop(lina, role, disabler).
prop(lion, role, disabler).
prop(necrophos, role, disabler).
prop(ogre_magi, role, disabler).
prop(oracle, role, disabler).
prop(outworld_destroyer, role, disabler).
prop(puck, role, disabler).
prop(rubick, role, disabler).
prop(shadow_demon, role, disabler).
prop(shadow_shaman, role, disabler).
prop(silencer, role, disabler).
prop(skywrath_mage, role, disabler).
prop(storm_spirit, role, disabler).
prop(techies, role, disabler).
prop(visage, role, disabler).
prop(void_spirit, role, disabler).
prop(warlock, role, disabler).
prop(windranger, role, disabler).
prop(winter_wyvern, role, disabler).
prop(witch_doctor, role, disabler).

% Jungle
prop(axe, role, jungle).
prop(lifestealer, role, jungle).
prop(lycan, role, jungle).
prop(sand_king, role, jungle).
prop(bloodseeker, role, jungle).
prop(lone_druid, role, jungle).
prop(ursa, role, jungle).
prop(batrider, role, jungle).
prop(chen, role, jungle).
prop(crystal_maiden, role, jungle).
prop(dark_seer, role, jungle).
prop(enchantress, role, jungle).
prop(engima, role, jungle).
prop(keeper_of_the_light, role, jungle).
prop(naturs_prophet, role, jungle).

% Durable
prop(abaddon, role, durable).
prop(alchemist, role, durable).
prop(axe, role, durable).
prop(beastmaster, role, durable).
prop(brewmaster, role, durable).
prop(bristleback, role, durable).
prop(centaur_warrunner, role, durable).
prop(chaos_knight, role, durable).
prop(clockwerk, role, durable).
prop(doom, role, durable).
prop(dragon_knight, role, durable).
prop(earth_spirit, role, durable).
prop(elder_titan, role, durable).
prop(huskar, role, durable).
prop(kunkka, role, durable).
prop(legion_commander, role, durable).
prop(lifestealer, role, durable).
prop(lycan, role, durable).
prop(mars, role, durable).
prop(night_stalker, role, durable).
prop(omniknight, role, durable).
prop(pudge, role, durable).
prop(slardar, role, durable).
prop(spirit_breaker, role, durable).
prop(sven, role, durable).
prop(tidehunter, role, durable).
prop(timbersaw, role, durable).
prop(tiny, role, durable).
prop(treant_protector, role, durable).
prop(underlord, role, durable).
prop(undying, role, durable).
prop(wraith_king, role, durable).
prop(faceless_void, role, durable).
prop(lone_druid, role, durable).
prop(medusa, role, durable).
prop(morphling, role, durable).
prop(pangolier, role, durable).
prop(razor, role, durable).
prop(spectre, role, durable).
prop(troll_warlord, role, durable).
prop(ursa, role, durable).
prop(viper, role, durable).
prop(bane, role, durable).
prop(enchantress, role, durable).
prop(necrophos, role, durable).
prop(ogre_magi, role, durable).
prop(visage, role, durable).

% Escape
prop(centaur_warrunner, role, escape).
prop(earth_spirit, role, escape).
prop(io, role, escape).
prop(lifestealer, role, escape).
prop(lycan, role, escape).
prop(magnus, role, escape).
prop(phoenix, role, escape).
prop(sand_king, role, escape).
prop(stardar, role, escape).
prop(snapfire, role, escape).
prop(spirit_breaker, role, escape).
prop(timbersaw, role, escape).
prop(treant_protector, role, escape).
prop(underlord, role, escape).
prop('anti-mage', role, escape).
prop(arc_warden, role, escape).
prop(bounty_hunter, role, escape).
prop(broodmother, role, escape).
prop(clinkz, role, escape).
prop(ember_spirit, role, escape).
prop(faceless_void, role, escape).
prop(hoodwink, role, escape).
prop(juggernaut, role, escape).
prop(meepo, role, escape).
prop(mirana, role, escape).
prop(monkey_king, role, escape).
prop(morphling, role, escape).
prop(naga_siren, role, escape).
prop(nyx_assassin, role, escape).
prop(pangolier, role, escape).
prop(phantom_assassin, role, escape).
prop(phantom_lancer, role, escape).
prop(riki, role, escape).
prop(slark, role, escape).
prop(spectre, role, escape).
prop(templar_assassin, role, escape).
prop(vengeful_spirit, role, escape).
prop(weaver, role, escape).
prop(batrider, role, escape).
prop(dark_seer, role, escape).
prop(dark_willow, role, escape).
prop(grimstroke, role, escape).
prop(invoker, role, escape).
prop(natures_prophet, role, escape).
prop(oracle, role, escape).
prop(puck, role, escape).
prop(queen_of_pain, role, escape).
prop(storm_spirit, role, escape).
prop(void_spirit, role, escape).
prop(windranger, role, escape).

% Pusher
prop(chaos_knight, role, pusher).
prop(dragon_knight, role, pusher).
prop(lycan, role, pusher).
prop(tiny, role, pusher).
prop(broodmother, role, pusher).
prop(clinkz, role, pusher).
prop(drow_ranger, role, pusher).
prop(juggernaut, role, pusher).
prop(lone_druid, role, pusher).
prop(luna, role, pusher).
prop(meepo, role, pusher).
prop(naga_siren, role, pusher).
prop(phantom_lancer, role, pusher).
prop(razor, role, pusher).
prop(terrorblade, role, pusher).
prop(troll_warlord, role, pusher).
prop(venomancer, role, pusher).
prop(chen, role, pusher).
prop(death_prophet, role, pusher).
prop(enchantress, role, pusher).
prop(enigma, role, pusher).
prop(invoker, role, pusher).
prop(jakiro, role, pusher).
prop(leshrac, role, pusher).
prop(natures_prophet, role, pusher).
prop(pugna, role, pusher).
prop(shadow_shaman, role, pusher).
prop(tinker, role, pusher).
prop(visage, role, pusher).

% Initiator
prop(alchemist, role, initiator).
prop(axe, role, initiator).
prop(beastmaster, role, initiator).
prop(brewmaster, role, initiator).
prop(bristleback, role, initiator).
prop(centaur_warrunner, role, initiator).
prop(chaos_knight, role, initiator).
prop(clockwerk, role, initiator).
prop(doom, role, initiator).
prop(dragon_knight, role, initiator).
prop(earth_spirit, role, initiator).
prop(earthshaker, role, initiator).
prop(elder_titan, role, initiator).
prop(huskar, role, initiator).
prop(kunkka, role, initiator).
prop(legion_commander, role, initiator).
prop(magnus, role, initiator).
prop(mars, role, initiator).
prop(night_stalker, role, initiator).
prop(phoenix, role, initiator).
prop(pudge, role, initiator).
prop(sand_king, role, initiator).
prop(slardar, role, initiator).
prop(spirit_breaker, role, initiator).
prop(sven, role, initiator).
prop(tidehunter, role, initiator).
prop(tiny, role, initiator).
prop(treant_protector, role, initiator).
prop(tusk, role, initiator).
prop(wraith_king, role, initiator).
prop(bloodseeker, role, initiator).
prop(ember_spirit, role, initiator).
prop(faceless_void, role, initiator).
prop(meepo, role, initiator).
prop(monkey_king, role, initiator).
prop(naga_siren, role, initiator).
prop(nyx_assassin, role, initiator).
prop(pangolier, role, initiator).
prop(vengeful_spirit, role, initiator).
prop(venomancer, role, initiator).
prop(viper, role, initiator).
prop(batrider, role, initiator).
prop(dark_seer, role, initiator).
prop(disruptor, role, initiator).
prop(enigma, role, initiator).
prop(lion, role, initiator).
prop(ogre_magi, role, initiator).
prop(puck, role, initiator).
prop(shadow_demon, role, initiator).
prop(shadow_shaman, role, initiator).
prop(silencer, role, initiator).
prop(storm_spirit, role, initiator).
prop(warlock, role, initiator).

